### ISSUE TITLE
How add metadata without creating a new file ?

### ISSUE THREAD

**Issue by cyr06** [moogar0880/PySubler#5]
How add metadata without creating a new file (~ "save" instead of "save as") ?
I use that code and I get a _show (1).mp4_

```
from subler import Subler
from subler.tools import AtomCollection
metadata = AtomCollection()
metadata['TV Show'] = 'show_name'
s = Subler('/Users/me/show.mp4', metadata=metadata.atoms)
s.tag()
```

**Comment by moogar0880** [comment]
Hey, so I've played around with this a bit and unfortunately it doesn't look like the SublerCLI provides that functionality. It looks like it will always create a `<title> (1)` file if the source and destination files have the same name. My guess is that it's a limitation of whatever API it's calling under the covers. 

I'd suggest doing something along these lines

```python
import os
import shutil
from subler import Subler
from subler.tools import AtomCollection
metadata = AtomCollection()
metadata['TV Show'] = 'show_name'

original_file_name = '/Users/me/show.mp4'
old_file_name = '/Users/me/show.mp4.old'

# move the file to denote it as the "old" file
shutil.move(original_file_name, old_file_name)

s = Subler(old_file_name, dest=original_file_name, metadata=metadata.atoms)
s.tag()

# clean up the un-tagged file
os.remove(old_file_name)
```

**Comment by cyr06** [comment]
Thank you for this code which is better that the one I used to get rid of the old file.
I thought I could save some time but I will launch my batch process while I take a nap ;)
Have a good day !
